# Generated by Django 5.2.7 on 2025-11-02 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='difficulty',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='workout',
            name='total_duration',
            field=models.IntegerField(default=0),
        ),
    ]
